name: GitHub Snake Animation

# When the workflow runs
on:
  schedule:
    - cron: '0 0 * * *'   # every day at midnight UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Generate the snake SVGs
      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Commit the generated SVGs back to the repo
      - name: Commit and push snake SVGs
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add dist/*
          git commit -m "Update GitHub Snake SVGs" || echo "No changes to commit"
          git push
